### ISSUE TITLE
Using package example results in todays day name not being displayed

### ISSUE THREAD

**Issue by raLaaaa** [JonasWanke/timetable#10]
Hey thanks for your awesome library!

I tried to setup your example in my local project and everything works fine so far except for the fact that the name of the current day does not get displayed in the header. A screenshot will clarify things:

![image](https://user-images.githubusercontent.com/12799722/83145849-bb6aed00-a0f5-11ea-8c2b-7d3b6cb73c4d.png)

I basically just copied the code of your example folder. Is this a bug or am I doing something wrong? I also added some events but that doesn't change anything.

This is my controller:

```dart
    _controller = TimetableController(
      // A basic EventProvider containing a single event.
      eventProvider: provider,
      initialTimeRange: InitialTimeRange.range(
        startTime: LocalTime(8, 0, 0),
        endTime: LocalTime(20, 0, 0),
      ),
      initialDate: LocalDate.today(),
      visibleRange: VisibleRange.days(3),
      firstDayOfWeek: DayOfWeek.monday,
    );
```
This is my build:

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          leading: IconButton(
            icon: Icon(Icons.arrow_back_ios, color: Colors.black),
            onPressed: () => Navigator.of(context).pop(),
          ),
          title: widget.args.roomId == null ? Text('TIMETABLE') : Text('TIMETABLE FOR ' + findRoomById(widget.args.roomId).name.toUpperCase()),
          actions: <Widget>[Padding(
              padding: EdgeInsets.only(top: 20.0),
              child: IconButton(
                icon: Icon(Icons.add),
                onPressed: () {

                },
                alignment: Alignment.center,
              ))],
          elevation: 0,
          centerTitle: true,
        ),
        body: Timetable<BasicEvent>(
          controller: _controller,
          eventBuilder: (event) => BasicEventWidget(event),
          allDayEventBuilder: (context, event, info) =>
              BasicAllDayEventWidget(event, info: info),
        ),
    );
  }
```

Any ideas what is going on? I might be doing something wrong. Maybe you can help me out here.

Cheers!

-----------

Currently using 0.2.1 of timetable.
Settings of my devices

Name: Pixel_API_R
CPU/ABI: Google Play Intel Atom (x86)
Path: C:\Users\.android\avd\Pixel_API_R.avd
Target: google_apis_playstore [Google Play] (API level R)
Skin: pixel_silver
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel
hw.lcd.width: 1080
image.androidVersion.codename: R
hw.initialOrientation: Portrait
image.androidVersion.api: 29
tag.id: google_apis_playstore
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Pixel API R
hw.gpu.mode: auto
hw.ramSize: 1536
PlayStore.enabled: true
fastboot.forceColdBoot: no
hw.cpu.ncore: 3
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 1920
vm.heapSize: 228
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images\android-R\google_apis_playstore\x86\
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: Pixel_API_R
hw.lcd.density: 420
hw.arc: false
hw.device.hash2: MD5:55acbc835978f326788ed66a5cd4c9a7
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google Play
runtime.network.latency: none
disk.dataPartition.size: 6442450944
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

**Comment by JonasWanke** [comment]
Thanks for the detailed description! As not only the current weekday indicator, but also the circle drawn around the current day of month isn't visible, I'd guess that your theme's primary color isn't visible on the background. You can resolve that by manually specifying a different primary color for timetable to use in it's theme ([TimetableThemeData.primaryColor](https://pub.dev/documentation/timetable/latest/timetable/TimetableThemeData/primaryColor.html)):

```dart
Timetable<BasicEvent>(
  controller: _controller,
  theme: TimetableThemeData(
    primaryColor: Colors.teal,
  ),
  // ...
)
```

> **Note:** You can also specify those colors more specifically, see `weekDayIndicatorDecoration` & `weekDayIndicatorTextStyle` for the upper text containing the day of week and `dateIndicatorDecoration` & `dateIndicatorTextStyle` for the day of month displayed below in the [documentation](https://pub.dev/documentation/timetable/latest/timetable/TimetableThemeData-class.html).

That should resolve your issue. If your theme's primary color isn't something like white or transparent, I'm not sure why this is happening though.

**Comment by raLaaaa** [comment]
Thanks for your quick reply! 
Ah, I didn't think about this one. Changing the primary color fixed it. '

Thanks a lot.
