### ISSUE TITLE
Change color of currently selected day in CompactMonthTimetable

### ISSUE THREAD

**Issue by tech-119** [JonasWanke/timetable#100]
How can currently selected date in [CompactMonthTimetable](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/CompactMonthTimetable-class.html) be changed?

In a way so that today date is always selected in its own colour (as it is now which is good), but for those manually selected dates in [CompactMonthTimetable](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/CompactMonthTimetable-class.html) to set some custom color?

![image](https://user-images.githubusercontent.com/88559046/129587699-55160786-b88b-49cf-8f01-1014a3eec685.png)

**Comment by JonasWanke** [comment]
If you already customize the `dateBuilder` of `MonthWidget`, you can customize/overwrite the style for each `DateIndicator`individually. Alternatively, you can customize the `themeData.dateIndicatorStyleProvider` and return the style you want for each day

**Comment by tech-119** [comment]
@JonasWanke I will try it tomorrow morning with customized `dateBuilder`.

 I have one more question related to dateBuilder style, when i applied custom `dateBuilder` i noticed dates from other months are not displayed in `MonthWidget` (neither as "enabled" or "disabled"), but only dates from currently displayed month are shown? For details i will post screenshot and code tomorrow morning

**Comment by JonasWanke** [comment]
Have a look at `monthWidgetStyle.showDatesFromOtherMonths` and `monthWidgetStyle.showDatesFromOtherMonthsAsDisabled`, which are used here:
https://github.com/JonasWanke/timetable/blob/9405c9c8aa4bc5ff0121f2d2b56f131db88e3635/lib/src/components/month_widget.dart#L45-L63

**Comment by tech-119** [comment]
@JonasWanke  I'm trying handle `MonthWidget` now and I run into few issues that i'm trying to solve:

1. FIRST ISSUE:
I'm not sure how to define color for currently selected date, as you suggested I tried to use `dateIndicatorStyleProvider` but I have to select date 2 times in order for changes to be applied visually, here is a short clip:

https://user-images.githubusercontent.com/88559046/129684469-ce4be150-ca00-47a6-9a20-209b2c32a9d3.mp4

**CODE**:
```dart
    dateIndicatorStyleProvider: (date) => DateIndicatorStyle(
      context,
      date,
      textStyle: TextStyle(color: _dateController.date.value == date ? Colors.white : Colors.black),
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        color: _dateController.date.value == date ? Colors.red : Colors.transparent
        ),
      ),
```

2. SECOND ISSUE:
I have navigated to January 2022, and there only 30 dates appears when it should be 31. I have also noticed same issue with February 2022 where it shows only 27 days instead of 28:

![image](https://user-images.githubusercontent.com/88559046/129684868-f47806d8-4daa-458a-91d9-1615efc90541.png)
![image](https://user-images.githubusercontent.com/88559046/129684884-7ca00340-6e58-4136-8a39-0ce1be429f67.png)

**Comment by JonasWanke** [comment]
Regarding the first issue: Is the underlying Date controller updated and only that part of the UI isn't updated? It might be a problem with your state management: You have to rebuild the widget for it to know that the lambda will return a different value.

Regarding the second issue: Please file a separate issue for that. If the problem isn't reproducible, please also include the relevant subset of your code.

**Comment by tech-119** [comment]
> Is the underlying Date controller updated and only that part of the UI isn't updated?

I haven't done my own coding here, I have tried to use what I already have and I see there is a `setState` in [onDateTap](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/TimetableCallbacks/onDateTap.html) callback (in `_updateVisibleDateRange` method):
```dart
child: Builder(builder: (context) {
  return DefaultTimetableCallbacks(
    callbacks: DefaultTimetableCallbacks.of(context)!.copyWith(
      onDateTap: (date) {
        _dateController.animateTo(date, vsync: this);
        _updateVisibleDateRange(PredefinedVisibleDateRange.day);
      },
    ),
    ``` where `_updateVisibleDateRange` is :
    ```dart
    void _updateVisibleDateRange(PredefinedVisibleDateRange newValue) {
    setState(() {
      _visibleDateRange = newValue;
      _dateController.visibleRange = newValue.visibleDateRange;
    });
  }
  ```

**Comment by JonasWanke** [comment]
`_dateController.animateTo` changes the value asynchronously. You can try to call `setState` after the animation is done

**Comment by tech-119** [comment]
@JonasWanke I have tried this way and it did worked:
```dart
onDateTap: (date) {
  _dateController.animateTo(date, vsync: this).then(
        (value) => _updateVisibleDateRange(
            PredefinedVisibleDateRange.day),
      );
},
```


https://user-images.githubusercontent.com/88559046/129695298-b0d832a7-2a83-4bd4-9f49-9c33a625afab.mp4


It does work but it changes only when animation completes (does not feel natural as it is with other calendars). Is there any way to make it so that it instantly changes style for newly selected date?

**Comment by JonasWanke** [comment]
You could use a separate `DateController` for that on which you call jump instead of animate. Alternatively, change the focus date and compare to it in the lambda you pass to the style.

**Comment by tech-119** [comment]
> focus date and compare to it in the lambda you pass to the style.

What would be focus date? And in this case with focus date i would not have to use `.then` function to change focus date after animation completes? 
```dart
onDateTap: (date) {
  _dateController.animateTo(date, vsync: this).then(
        (value) => _updateVisibleDateRange(
            PredefinedVisibleDateRange.day),
      );
},
```

**Comment by JonasWanke** [comment]
A separate field next to the controller that you always set to the date that should be highlighted.

Exactly. Just set it synchronously before or after calling animate and then call `setState` synchronously as well

**Comment by tech-119** [comment]
> A separate field next to the controller that you always set to the date that should be highlighted

Which separate field? Isn't is from a function `_updateVisibleDateRange` ? I do not understand how exactly is selected date highligted

```dart
  void _updateVisibleDateRange(PredefinedVisibleDateRange newValue) {
    setState(() {
      _visibleDateRange = newValue;
      _dateController.visibleRange = newValue.visibleDateRange;
    });
  }
  ```

**Comment by JonasWanke** [comment]
According to https://github.com/JonasWanke/timetable/issues/100#issuecomment-900070715, you do the highlighting yourself. Instead of basing that on `_dateController.date.value`, you can create a separate field for storing the date that should be displayed as selected

**Comment by tech-119** [comment]
> _dateController.date.value

oh a regular state value, thank you I tried and it works!

**Comment by tech-119** [comment]
> timetable/lib/src/components/month_widget.dart

I have removed `themeMode: overrideState.themeMode` from Material App and I use my own theme, and now i'm trying to override `CompactMonthTimetable`'s `MonthWidget`, specifically:
```dart
  CompactMonthTimetable(
monthBuilder: (context, month) => Material(
  color: Colors.white,
  child: MonthWidget(
    month,
    dateBuilder: (context, date) {
      assert(date.isValidTimetableDate);

      return DateIndicator(
        date,
        style: DateIndicatorStyle(
          context,
          date,
          textStyle: TextStyle(
            color: selectedDate == date
                ? Colors.white
                : Colors.black,
          ),
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: selectedDate == date
                ? AppColors.primaryColor
                : Colors.transparent,
          ),
        ),
      );
    },
    weekBuilder: (context, week) => SizedBox.shrink(),
  ),
),
),
```

the issue is that now I don't know how to set dates from other months as disabled (different color)?
![image](https://user-images.githubusercontent.com/88559046/129923713-597d64af-9b3d-4da1-a0ed-66a119da41e2.png)

**Comment by JonasWanke** [comment]
You can check whether `date.firstDayOfMonth == month` and set the text style based on that

**Comment by tech-119** [comment]
> You can check whether `date.firstDayOfMonth == month` and set the text style based on that

Thanks for reply I will check it tomorrow morning and reply back here

**Comment by tech-119** [comment]
```dart
style: DateIndicatorStyle(
  context,
  date,
  textStyle: TextStyle(
    color: selectedDate == date
        ? Colors.white
        : date.firstDayOfMonth == month ? Colors.black : Colors.grey[500],
  ),
  ``` Worked! Thank you @JonasWanke
