### ISSUE TITLE
Issue with displaying dates in MonthWidget

### ISSUE THREAD

**Issue by tech-119** [JonasWanke/timetable#101]
**Describe the bug**
I have been scrolling to next year and noticed only 30 days for January 2022 and only 27 days for Februray 2022 when it should be 31 days for January and 28 for February:

| January 2022  | February 2022  |
| :------------: | :------------: |
| ![image](https://user-images.githubusercontent.com/88559046/129684868-f47806d8-4daa-458a-91d9-1615efc90541.png) | ![image](https://user-images.githubusercontent.com/88559046/129684884-7ca00340-6e58-4136-8a39-0ce1be429f67.png) |

To reproduce the issue clone example project from this github repository and scroll to year 2022:
[Official Timetable example](https://github.com/JonasWanke/timetable/tree/main/example)

**Environment:**

- Device:  Android Emulator Pixel_2_API_29 x86_64
- Package version:  [Timetable 1.0.0-alpha.5](https://pub.dev/packages/timetable/versions/1.0.0-alpha.5)

**Comment by tech-119** [comment]
Did you take a look into this issue Jonas?

**Comment by JonasWanke** [comment]
Fixed and published as part of [v1.0.0-alpha.6](https://pub.dev/packages/timetable/versions/1.0.0-alpha.6/changelog#100-alpha6--2021-09-29)
