### ISSUE TITLE
Missing parameter? when cold starting

### ISSUE THREAD

**Issue by laguerreuy** [JonasWanke/timetable#105]
**Describe the bug**
I get this issue when trying to start for the first time

_AppData/Local/Pub/Cache/hosted/pub.dartlang.org/timetable-1.0.0-alpha.5/lib/src/time/zoom.dart:621:43: Error: Too few positional arguments: 2 required, 1 given.
          focalPointDelta > computeHitSlop(pointerDeviceKind))_

The problem is fixed if I add null as second parameter. I updated the code as follows:

      _if (spanDelta > computeScaleSlop(pointerDeviceKind) ||
          focalPointDelta > computeHitSlop(pointerDeviceKind, null))_

My programming skills are basic, please ignore if the issue is caused by a mistake on my side. I would appreciate some guide in that case.

**Environment:**
- Device:  <Mi Note 10>
- OS version:  <Android 11>

**Comment by JonasWanke** [comment]
Fixed and published as part of [v1.0.0-alpha.6](https://pub.dev/packages/timetable/versions/1.0.0-alpha.6/changelog#100-alpha6--2021-09-29)
