### ISSUE TITLE
The minimum duration of an event is 30 minutes.

### ISSUE THREAD

**Issue by alexfdz55** [JonasWanke/timetable#108]
The minimum duration of an event is 30 minutes.
It would be good
to be able to put the duration of an event less than 30 minutes.

**Comment by JonasWanke** [comment]
I'm assuming you are talking about versions v0.2.9 and before, as opposed to the refactored/rewritten 1.0.0 pre-release versions? In that case, you can modify the minimum duration using the theme's [`partDayEventMinimumDuration`](https://pub.dev/documentation/timetable/latest/timetable/TimetableThemeData/partDayEventMinimumDuration.html).

**Comment by JonasWanke** [comment]
I'm closing this issue for now. If the above doesn't answer your question or you have a follow-up question, feel free to reopen it.
