### ISSUE TITLE
Detect when page in MultiDateTimetable completes

### ISSUE THREAD

**Issue by ghost** [JonasWanke/timetable#110]
How to detect when page completely changes? For example to get a callback not after you just begin with swiping, nor when you release a press while swiping, but when animation of page swipe ends? If you were to start swiping form one page to another and while on the middle between two pages you release a press, page will continue with animation to second page, and when it finishes animation i would like to get a callback.

Reason why I'm asking is because I would like to fetch events from server whenever user swipes to new page, and issue with `_dateController.addListener()` is because it triggers a callback somewhat good when you swipe to next page, but when you try to swipe to previous page listener is triggered almost instantly as you being to swipe to previous page.

I though to use NotificationListener, and it does work properly for horizontal swiping but issues with this approach is that it also detects when scrolling is active vertically, what i need is only to listen when horizontal page swiping ends
```dart
void handleScrollListener(ScrollNotification scrollNotification) {
  if (scrollNotification is ScrollStartNotification) {
    print("SCROLLING");
  } else if (scrollNotification is ScrollEndNotification) {
    print("STOPPED SCROLLING!");
  }
}

@override
Widget build(BuildContext context) {
  return NotificationListener<ScrollNotification>(
    onNotification: (scrollNotification) {
      SchedulerBinding.instance!.addPostFrameCallback(
          (_) => handleScrollListener(scrollNotification));
      return true;
    },
    child: Stack(
      children: [
        TimetableConfig<EventModel>(
```

**Comment by JonasWanke** [comment]
As part of [v1.0.0-alpha.11](https://pub.dev/packages/timetable/versions/1.0.0-alpha.11/changelog#100-alpha11--2023-01-24), I've added [`dateController.value.activity`](https://pub.dev/documentation/timetable/1.0.0-alpha.11/timetable/DatePageValueWithScrollActivity/activity.html), which is an instance of [`DateScrollActivity`](https://pub.dev/documentation/timetable/1.0.0-alpha.11/timetable/DateScrollActivity-class.html). The value can be from one of three subclasses: [`DragDateScrollActivity`](https://pub.dev/documentation/timetable/1.0.0-alpha.11/timetable/DragDateScrollActivity-class.html), [`DrivenDateScrollActivity`](https://pub.dev/documentation/timetable/1.0.0-alpha.11/timetable/DrivenDateScrollActivity-class.html), or [`IdleDateScrollActivity`](https://pub.dev/documentation/timetable/1.0.0-alpha.11/timetable/IdleDateScrollActivity-class.html). Hence, you now have the option to, e.g., ignore updates that stem from an animation. But you can do even better: [`drivenDateScrollActivity`](https://pub.dev/documentation/timetable/1.0.0-alpha.11/timetable/DrivenDateScrollActivity-class.html) exposes a field [`target`](https://pub.dev/documentation/timetable/1.0.0-alpha.11/timetable/DrivenDateScrollActivity/target.html), so you can prefetch events for the target range of an animation while it's still ongoing.
