### ISSUE TITLE
How to change color of event text

### ISSUE THREAD

**Issue by tech-119** [JonasWanke/timetable#111]
How to change text color of event? (currently it is black for all events

![image](https://user-images.githubusercontent.com/88559046/131814076-7e9d98d3-4623-4cfb-aa60-f97749f14735.png)

**Comment by paolovalerdi** [comment]
You can create your very own widget (or copy-paste the `BasicEventWidget` one) and theme it however you like

**Comment by tech-119** [comment]
> You can create your very own widget (or copy-paste the `BasicEventWidget` one) and theme it however you like

I checked it and it seems as solution, thanks for answer!
