### ISSUE TITLE
Swiping to different days does not work when dragging with mouse pointer

### ISSUE THREAD

**Issue by mbartnik** [JonasWanke/timetable#113]
Hello,

On web when trying to change a week by clicking left mouse button and trying to swipe, nothing happens. It works when scrolling horizontally with a touchpad, it worked in both situations on version 0.2.9 (I'm trying to switch to 1.0.0-alpha.6).
I have confirmed that the issue also exists in the example provided in the repository.

**Comment by JonasWanke** [comment]
Hi, thanks for filing this issue, and sorry for the delay. I can confirm that that's the case, but I am unsure whether we would want Timetable to be scrollable horizontally by dragging it with the mouse. For example, Google Calendar and Microsoft Outlook don't support that either and instead offer buttons (both) and keyboard shortcuts (only Google Calendar). Dragging with the mouse is instead reserved for creating a new event for that time range (though only for dragging vertically, not horizontally).

Both buttons and keyboard shortcuts for navigation could already be implemented on top of Timetable, but we could also support them out of the box. Do you think that horizontal dragging with the mouse is necessary or that these alternatives suffice?

**Comment by mbartnik** [comment]
Thank you for replying. This feature is no longer very important for me, but since it works in stable version, there might be other developers that rely on it.

**Comment by JonasWanke** [comment]
Then I'm gonna close this issue for now. If anyone is missing this behavior when updating to v1.0.0, feel free to comment on or reopen this issue.
