### ISSUE TITLE
TimeZoom's `_ScrollPositionWithSingleContext` doesn't support `pointerScroll`

### ISSUE THREAD

**Issue by abel-123** [JonasWanke/timetable#115]
**Describe the bug**
When trying to scroll with the mouse wheel on desktop (flutter web), timetable does not scroll and throws an error.

> ======== Exception caught by gesture library===============
The following UnsupportedError was thrown while resolving a PointerSignalEvent:
Unsupported operation: TimeZoom's `_ScrollPositionWithSingleContext` doesn't support `pointerScroll`.
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
packages/timetable/src/time/zoom.dart 809:5                                                                                    pointerScroll
packages/flutter/src/widgets/scrollable.dart 717:16                                                                            [_handlePointerScroll]
packages/flutter/src/gestures/pointer_signal_resolver.dart 88:7                                                                resolve
packages/flutter/src/gestures/binding.dart 445:29                                                                              handleEvent
packages/flutter/src/gestures/binding.dart 419:14                                                                              dispatchEvent
packages/flutter/src/rendering/binding.dart 322:11                                                                             dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                                                               [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                                                               handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                                                               [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                                                              [_handlePointerDataPacket]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1020:13               invoke1
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 184:5                 invokeOnPointerDataPacket
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 130:39                    [_onPointerData]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 310:14                    [_handleWheelEvent]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 574:7                     <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 290:87                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
Event: _TransformedPointerScrollEvent#9dbd4(position: Offset(827.0, 649.0), scrollDelta: Offset(-0.0, 100.0))
  position: Offset(827.0, 649.0)
  scrollDelta: Offset(-0.0, 100.0)
============================================================

**Environment:**
* OS version:  Windows 11
* Flutter version:  e.g. 2.8.1
* Package version:  1.0.0-alpha.6

**Comment by JonasWanke** [comment]
Fixed and published as part of [v1.0.0-alpha.7](https://pub.dev/packages/timetable/versions/1.0.0-alpha.7/changelog#100-alpha7--2022-04-23) ([`1a286f2`](https://github.com/JonasWanke/timetable/commit/1a286f2e80178efddaa5ce3cc44aaf9e7df5b55c))
