### ISSUE TITLE
Seperate scroll bar for time column

### ISSUE THREAD

**Issue by abel-123** [JonasWanke/timetable#116]
**Describe the bug**
The time column shows a second scroll bar when I hold down the left button and drag up/ down (flutter web). When holding the left scrollbar (hold left mouse button on scroll bar), the time column can be scrolled separately from the events column (see screenshots).

**Screenshots**
Two scroll bars:
![image](https://user-images.githubusercontent.com/83268410/155667265-9dd74d82-1710-4a7b-b9e0-59fa23491703.png)

Time column on the left is misaligned after scrolling it without scrolling the events:
![image](https://user-images.githubusercontent.com/83268410/155667585-955b1737-3813-43c1-a3fb-d91b8183d361.png)

**Environment:**
* OS version:  Windows 11
* Flutter version:  2.8.1
* Package version:  1.0.0-alpha.6

**Comment by JonasWanke** [comment]
Fixed and published as part of [v1.0.0-alpha.7](https://pub.dev/packages/timetable/versions/1.0.0-alpha.7/changelog#100-alpha7--2022-04-23)
