### ISSUE TITLE
Remove Time of timetable

### ISSUE THREAD

**Issue by cedricDevWP** [JonasWanke/timetable#118]
Hi,

I am using the library to have a schedule with only daily events. So the hours on the left have no use. It would be nice to be able to hide them.

**Comment by JonasWanke** [comment]
Assuming you're using `MultiDateTimetable`, you can override its `contentBuilder` (responsible for the lower part including the time indicators and part-day events):

```dart
MultiDateTimetable<BasicEvent>(
  contentBuilder: (context, onLeadingWidthChanged) =>
      MultiDateTimetableContent<BasicEvent>(leading: SizedBox.shrink()),
  // By default, the week indicator in the header gets the same with as the
  // `TimeIndicators` as reported by `onLeadingWidthChanged` above. If that is
  // not called, you can manually size the week indicator.
  headerBuilder: (context, leadingWidth) =>
      MultiDateTimetableHeader<BasicEvent>(
    leading: SizedBox(
      width: 64,
      child: Center(child: WeekIndicator.forController(null)),
    ),
  ),
)
```

However, if you don't have part-day events at all, you can also use `MultiDateTimetableHeader` by itself (still wrapped in a `TimetableConfig`). This is the upper part of `MultiDateTimetable` that, by default, contains a week indicator, date headers, and all-day events).

**Comment by cedricDevWP** [comment]
Thank you for your prompt response.

is it possible by the same process to replace the hours with text? for example have people's names instead of hours and then the event in front? Like having a task schedule for each person

**Comment by JonasWanke** [comment]
You can construct `TimeIndicators` with custom `TimeIndicatorsChild`ren that contain a person's name instead of the time.

Alternatively, you could construct multiple `MultiDateTimetableHeader`s that all use the same `DateController` (and, hence, are scrolled in sync):

```dart
TimetableConfig<BasicEvent>(
  dateController: dateController,
  allDayEventBuilder: (context, event, info) =>
      BasicAllDayEventWidget(event, info: info),
  child: Column(children: [
    // Shows the date for every day
    DatePageView(
      shrinkWrapInCrossAxis: true,
      builder: (context, date) => DateHeader(date),
    ),
    // One for every person:
    DefaultEventProvider(
      eventProvider: eventProviderForPerson0,
      child: MultiDateEventHeader<BasicEvent>(),
    ),
    DefaultEventProvider(
      eventProvider: eventProviderForPerson1,
      child: MultiDateEventHeader<BasicEvent>(),
    ),
    DefaultEventProvider(
      eventProvider: eventProviderForPerson2,
      child: MultiDateEventHeader<BasicEvent>(),
    ),
  ]),
)
```
<sup>(Code is not tested)</sup>

Instead of a `Column`, you could also use a `Table` or some other widget that allows you to put the people's names in front of each row.

**Comment by JonasWanke** [comment]
I'm closing this issue for now. If the above doesn't answer your question or you have a follow-up question, feel free to reopen it.
