### ISSUE TITLE
Alternative to `currentlyVisibleDates`?

### ISSUE THREAD

**Issue by IoanaAlexandru** [JonasWanke/timetable#119]
After the package was reworked, the `DateController` no longer has `currentlyVisibleDates`. I couldn't find any clean way to find what the dates are, and resorted to looking at the pages manually. I think it would be nice to have this functionality back. (Also, for the record, the documentation still states that you can use `DateController` to check the currently visible dates)

My use-case is that I'd like to show a toast when the user presses the "Show today" button when they're already on the current week. Before the update, the condition was simply `_controller.currentlyVisibleDates.contains(LocalDate.today())`. After the update, I did the following:

```dart
  bool showingCurrentWeek() {
    final todayPage = DateTime.now().toUtc().atStartOfDay.datePage;
    final currentPage = _dateController.value.page;
    final visibleDayCount = _dateController.visibleRange.visibleDayCount;
    return currentPage <= todayPage &&
        todayPage <= currentPage + visibleDayCount - 1;
  }
```

**Comment by JonasWanke** [comment]
As part of [v1.0.0-alpha.7](https://pub.dev/packages/timetable/versions/1.0.0-alpha.7/changelog#100-alpha7--2022-04-23), there are now `dateController.visibleDates `, `datePageValue.visibleDates`, `.firstVisibleDate`, `.firstVisiblePage`,`.lastVisibleDate`, and `.lastVisiblePage`
