### ISSUE TITLE
Expose Offset to DateTime conversion

### ISSUE THREAD

**Issue by TruFelix** [JonasWanke/timetable#124]
At the moment the functionality to convert a Offset to the appropriate DateTime when dragging Events (using `PartDayDraggableEvent`) is not exposed, `_DragInfos` is private. It would be beneficial to expose this functionality, to allow for a better customization and handling custom drag'n'drop

Possible Solution:
It would be enough to just expose the `_DragInfos` class, by doing so, you could just call `DragInfos.resolveOffset(...)` inside of a custom Draggable. Also it would be great, to have the possibility to specify, which `DragInfos` instance should be used to be able to call this functionality from another subtree.

**Comment by JonasWanke** [comment]
I've added this as part of [v1.0.0-alpha.9](https://pub.dev/packages/timetable/versions/1.0.0-alpha.9/changelog#100-alpha9--2022-08-19), see the [updated README section about Drag and Drop](https://pub.dev/packages/timetable/versions/1.0.0-alpha.9#drag-and-drop). In addition, you can manually resolve offsets using [`geometryKey.currentState!.resolveOffset(globalOffset)`](https://pub.dev/documentation/timetable/1.0.0-alpha.9/timetable/MultiDateContentGeometry/resolveOffset.html).

**Comment by TruFelix** [comment]
Cool! Thank you!
