### ISSUE TITLE
isValidTimetableDateTime should provide a more precise assertion error

### ISSUE THREAD

**Issue by raLaaaa** [JonasWanke/timetable#127]
During development one could encounter having a date with is an invalid time table date.
I think that an date is none UTC conform is probably the most likely reason. But it could also be null.
Asserting the value at various points with `isValidTimetableDateTime` is a great way to ensure this does not happen during development how ever if this happens the developer can not be certain for what reason it is not since there is no specific assertion message attached.

I took a look at the code and I'm not quite sure if this is an easy fix due to the nature of assertions nor am I quite sure if this is really something the library should do for the developer. Hinting him to the assertion error(s) quite does the task. 

How ever it would be quite convenient when you believe you are searching for null values in your code but the date is simply UTC formatted.

What do you think?

**Comment by JonasWanke** [comment]
`dateTime.isValidTimetableDateTime` only checks that the `DateTime` has `isUtc` set. For nullable `DateTime`s, `null` is also allowed. This is true for all `isValidTimetable…` checks.

I can add a message (or, maybe, use [`FlutterError`](https://api.flutter.dev/flutter/foundation/FlutterError-class.html)) to this and other checks to make clearer what is expected of these values, similar to the note in the README.

**Comment by raLaaaa** [comment]
I don't think this has high priority. This is more a convenience point but I still believe that it might be helpful. I might help you out if you are interested. Adding an optional error message to assertions should be pretty straight forward.

**Comment by JonasWanke** [comment]
I've added detailed error messages (using [FlutterError](https://api.flutter.dev/flutter/foundation/FlutterError-class.html)) as part of [v1.0.0-alpha.9](https://pub.dev/packages/timetable/versions/1.0.0-alpha.9/changelog#100-alpha9--2022-08-19).
