### ISSUE TITLE
Overriding `==` in event instance leads to paint/layout exception

### ISSUE THREAD

**Issue by TatsuUkraine** [JonasWanke/timetable#129]
**Describe the bug**
`Event` class doesn't override `==`, which sometime may lead to an unnecessary layout. At the same time if you try to extend from `Event` and override `==` and `hashCode` to prevent unnecessary layout and paint, next time flutter try to rebuild the tree it will lead to
```
The _DayEventsLayoutDelegate<...> custom multichild layout delegate tried to lay out a non-existent child.
```

It happens because the entire instance is used for ID for item in `CustomMultiChildLayout`. So next time Flutter tries to find child by ID it may fail since the instance (not values) may be different already, nevertheless event itself doesn't change

**Environment:**
* OS version:  Android 13
* Flutter version:  3.3.0
* Package version:  1.0.0-alpha.10

**Comment by TatsuUkraine** [comment]
hm, it might be a problem in my code, closing it for now

**Comment by MasterHiei** [comment]
@TatsuUkraine Hi, i'm facing the same Issue. Could you tell me how did you fix this?

**Comment by TatsuUkraine** [comment]
@MasterHiei sorry, can't remember on 100% what I did)
here is a code sample similar to what I did, I think I fixed it by adding `debugFillProperties` override + equality and hashCode override (but I'm not sure)
```dart
@immutable
class TimeTableEvent extends Event {
  final String eventId;

  @override
  bool get isAllDay => false;

  const TimeTableEvent(this.eventId, DateTime startTime, DateTime endTime)
      : super(start: startTime, end: endTime);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeTableEvent &&
          eventId == eventId &&
          start == other.start &&
          end == other.end &&
          runtimeType == other.runtimeType;

  @override
  int get hashCode => eventId.hashCode ^ start.hashCode ^ end.hashCode;

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty('id', eventId)); /// <--- This line
  }
}
```

**Comment by TatsuUkraine** [comment]
but I can't say if it was a fix, it was a long time ago)

**Comment by MasterHiei** [comment]
@TatsuUkraine Oops, my hasCode caused it and it works now.
Thanks for saving my time :)
