### ISSUE TITLE
TimeZoom animation

### ISSUE THREAD

**Issue by HaneenAhmedMohy** [JonasWanke/timetable#130]
Is Timezoom Animation supported on the web ? and if not will it be supported soon?

**Comment by JonasWanke** [comment]
Yes, animating the `TimeZoom` widget is supported on all platforms. You can animate it using [`timeController.animateTo(…)`](https://pub.dev/documentation/timetable/1.0.0-alpha.10/timetable/TimeController/animateTo.html) or [`timeController.animateToShowFullDay(…)`](https://pub.dev/documentation/timetable/1.0.0-alpha.10/timetable/TimeController/animateToShowFullDay.html)

**Comment by HaneenAhmedMohy** [comment]
and is it zooming the timeTable range(out and in) in all platforms as well?

**Comment by JonasWanke** [comment]
This package doesn't use any platform-specific code. Zooming the time (vertically) uses a `RawGestureDetector` with a (slightly modified) `ScaleGestureRecognizer`, so it should work on all platforms that support multiple simultaneous pointers

**Comment by JonasWanke** [comment]
I'm going to close this. Feel free to add a comment or reopen this issue if you have any further questions!
