### ISSUE TITLE
MultiDateScrollPosition cannot change controllers once created

### ISSUE THREAD

**Issue by georgiossalon** [JonasWanke/timetable#141]
In my app I have a FlowBuilder Widget (using Provider), which pushes new routes.

As a child, I have a timetable widget. When I tap on a BasicEventWidget, I Navigate to a new page.

```
   eventBuilder: (context, shift) => BasicEventWidget(
            shift,
            onTap: () =>
                context.flow<ShiftsFlowState>().selectShift(shift.id as String),
          ),
```

This is were I get the following error: 'MultiDateScrollPosition cannot change controllers once created.'

After commenting out the assert, the error is not being shown and the timetable is still working:

```
    // assert(
    //   linkedPosition.owner == this,
    //   'MultiDateScrollPosition cannot change controllers once created.',
    // );
```

You might have to check the code within the didChangeDependencies in the date_page_view.dart. and perhaps move the controller logic within the didUpdateWidget.

- OS version:  
- Flutter version:  3.3.9 stable
- Package version:  1.0.0-alpha11

**Comment by JonasWanke** [comment]
This is fixed as part of [v1.0.0-alpha.12](https://pub.dev/packages/timetable/versions/1.0.0-alpha.12/changelog#100-alpha12--2023-05-16)
