### ISSUE TITLE
animateToToday() doesn't work correctly for May 1st 2020

### ISSUE THREAD

**Issue by IoanaAlexandru** [JonasWanke/timetable#2]
This is reproducible with the example app, by just removing the `visibleRange` parameter in the controller (so leaving it on the default 7 days).

For some reason, today `animateToToday` brings the week of May 4th-10th into view instead of the week of April 27th-May 3rd. This is also the default page that the timetable opens on.

**Comment by JonasWanke** [comment]
Fixed and released in v0.1.2
