### ISSUE TITLE
Event size doesn't fill all remaining space

### ISSUE THREAD

**Issue by TatsuUkraine** [JonasWanke/timetable#29]
**Describe the bug**
All events in a day column has same size if at least one event overlaps all

#### Steps to reproduce:
Define events with next hour ranges:
12-16
12-13
12-13
12-13
15-16

You will notice that last item (15-16) will have width equals to thinner event 

**Screenshots**
<img width="143" alt="Снимок экрана 2020-07-11 в 00 45 18" src="https://user-images.githubusercontent.com/621542/87205304-ced1c080-c30f-11ea-8806-f51f5aeaba19.png">

**Environment:**

- Device:  --
- OS version:  --
- Package version:  0.2.5

**Comment by TatsuUkraine** [comment]
@JonasWanke wanted to ask, is possible to disable overlay positioning? According to code, it's impossible, but maybe I'm not something

**Comment by JonasWanke** [comment]
That's not yet possible, but something I can add easily

**Comment by TatsuUkraine** [comment]
@JonasWanke it will be awesome, I can create a ticket when I get to the computer if you want to. The case here, that I have a content in an event, and size of the start portion is basically unknown.

**Comment by JonasWanke** [comment]
@TatsuUkraine I've created a new issue with a suggestion of how this could be implemented.
