### ISSUE TITLE
Customizable event stacking

### ISSUE THREAD

**Issue by JonasWanke** [JonasWanke/timetable#31]
A few users mentioned the need for customizable event stacking/overlap behavior (https://github.com/JonasWanke/timetable/issues/29#issuecomment-657038699, https://github.com/JonasWanke/timetable/issues/17#issuecomment-657079973). I'd like to add two new properties (shown with their default values) to `TimetableThemeData`:

- `bool enablePartDayEventStacking = true`: If set to `true`, intersecting events may be stacked if their start values differ by at least the following value. If set to `false`, intersecting events will always be shown next to each other and not overlap.
- `Period partDayEventMinimumDeltaForStacking = Period(minutes: 15)`: Two events whose start values differ by this value or more can be stacked by the layout algorithm. If the difference is less, they will be shown next to each other.

**Comment by TatsuUkraine** [comment]
Just curious, if it possible to add these props to event itself, rather then to theme?

**Comment by TatsuUkraine** [comment]
So each event can define if it can be overlayed or not. JFI, I'm fine with theme props) just curious if it possible) I can imagine that in some cases , when event has info that shouldn't be overlayed for any cost, and some less critical info, that can be overlayed, dev could define overlay delta based on the size of critical info that he want to show

**Comment by TatsuUkraine** [comment]
I haven't seen this particular feature (with event based delta rather than global time table config) anywhere, but it might be much more flexible comparing to just global (Theme) config

If it requires a lot of time investment - ignore my comments 😁

**Comment by JonasWanke** [comment]
@TatsuUkraine That would be possible, but I plan to develop a new layout algorithm (see #32 — I have to remember to open issues for things I've planned…) so I don't think adding such a property to events directly is worth the effort (for now).

**Comment by TatsuUkraine** [comment]
@JonasWanke sure, np) approach that you suggested totally solves my issue)
