### ISSUE TITLE
Update events displayed functions of the selected day range

### ISSUE THREAD

**Issue by kbups** [JonasWanke/timetable#44]
Hello,
Very good job for this plugin!
Do you know how to update the events displayed functions of the visible days?
For example, I only display a day with VisibleRange.days(1) and I would like to automatically get and display events function of the selected day (when the user scrolls horizontally). Is there some callback function when page (relative to one day in my case) changed?
Thanks in advance for your reply.

**Comment by TatsuUkraine** [comment]
If I get you right, you can use stream event provider. Getter will be invoked each time when visible date range is changes. It expects that this method will return stream with Event collection, that should be displayed in the time table. Does it answers your question or I missing something?

**Comment by TatsuUkraine** [comment]
https://pub.dev/documentation/timetable/latest/timetable/EventProvider/EventProvider.stream.html

**Comment by TatsuUkraine** [comment]
If you need to just track visible date changes timetable controller provides bunch of listenable objects, that you can subscribe to https://pub.dev/documentation/timetable/latest/timetable/TimetableController-class.html

**Comment by JonasWanke** [comment]
Sorry for the delay and thanks for @TatsuUkraine for the quick response! [`EventProvider.stream`](https://pub.dev/documentation/timetable/latest/timetable/EventProvider/EventProvider.stream.html) indeed is the recommended way to supply events based on which dates are currently visible. To just track the visible dates (independently of the events to display), check out [`TimetableController.currentlyVisibleDatesListenable`](https://pub.dev/documentation/timetable/latest/timetable/TimetableController/currentlyVisibleDatesListenable.html).

@kbups Does this solve your question?
