### ISSUE TITLE
First Date of the Week

### ISSUE THREAD

**Issue by repsajanboy** [JonasWanke/timetable#53]
Hi guys, been using your package and it so great, it help me achieve a certain task that needed to be done. Just want to ask if there a way to get the first date of the week in the calendar. Example, im implementing VisibleRange.week(), and initialDate is LocalDate.today() I needed to get the value of the first day of the week, like now October 3-9, 2020 is visible in my timetable so i needed to get Oct. 3, 2020 and then when I scroll horizontally to next week the timetable will now display Oct. 10 - 16, 2020 and now I needed to get the value of Oct 10. is it possible?

**Comment by IoanaAlexandru** [comment]
`TimetableController` has a getter named `currentlyVisibleDates` which does what you want. Just call `controller.currentlyVisibleDates.start` to get the first day of the currently visible week!

**Comment by repsajanboy** [comment]
Yes, thank you I managed to got it, what is the correct way to format LocalDate? Because now I am getting a return value of Saturday, 03 October 2020, and what i need is 10/3/2020. thanks in advance

**Comment by IoanaAlexandru** [comment]
Check out `LocalDate`'s `toString` method. You can provide it with a pattern. I think you need something like `date.toString('MM/dd/yyyy')`. You can read more in the [Noda time documentation](https://nodatime.org/1.4.x/userguide/localdate-patterns), which the `time_machine` package is based on.
