### ISSUE TITLE
Getting Bottom Overflow error if all day event count is large

### ISSUE THREAD

**Issue by rohitbhoite** [JonasWanke/timetable#63]
**Describe the bug**
I am working on a flutter app where I need to show all day events in a timetable view. Its working for small number of events but if the event count is large then getting attached error 
![Screenshot_2021-02-28-16-05-29-09_6dc36f560add45efed6f283f9bcff7de](https://user-images.githubusercontent.com/13239043/109416099-33967400-79e2-11eb-87be-fc7bade3b43c.jpg)

- Device: Realme 7
- OS version:  Android 10
- Package version:  0.2.8(Cannot use 0.2.9 as it has breaking flutter version dependency)

**Comment by JonasWanke** [comment]
I've added this as part of [v1.0.0-alpha.9](https://pub.dev/packages/timetable/versions/1.0.0-alpha.9/changelog#100-alpha9--2022-08-19). You can now specify [`multiDateEventHeaderStyle.maxEventRows`](https://pub.dev/documentation/timetable/1.0.0-alpha.9/timetable/MultiDateEventHeaderStyle/maxEventRows.html) (defaults to showing up to three rows plus one with overflow indicators) and [`multiDateTimetableStyle.maxHeaderFraction`](https://pub.dev/documentation/timetable/1.0.0-alpha.9/timetable/MultiDateTimetableStyle/maxHeaderFraction.html) (defaults to `0.5`). You can react to taps on these overflows using [`timetableCallbacks.onMultiDateHeaderOverflowTap`](https://pub.dev/documentation/timetable/1.0.0-alpha.9/timetable/TimetableCallbacks/onMultiDateHeaderOverflowTap.html) or customize the overflow widgets themselves using [`defaultEventBuilder.allDayOverflowBuilder`](https://pub.dev/documentation/timetable/1.0.0-alpha.9/timetable/DefaultEventBuilder/allDayOverflowBuilder.html) (builds [`MultiDateEventHeaderOverflow`](https://pub.dev/documentation/timetable/1.0.0-alpha.9/timetable/MultiDateEventHeaderOverflow-class.html) by default).
