### ISSUE TITLE
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

### ISSUE THREAD

**Issue by jgmartinss** [JonasWanke/timetable#7]
**Describe the bug**
After running the example...

 - '_EventParentData' is from 'package:timetable/src/header/all_day_events.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/timetable-0.2.0/lib/src/header/all_day_events.dart').
 - 'RenderObjectWidget' is from 'package:flutter/src/widgets/framework.dart' ('../../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try changing type arguments so that they conform to the bounds.
class _EventParentDataWidget<E extends Event>
      ^
../../flutter/packages/flutter/lib/src/widgets/framework.dart:1439:33: Context: This is the type variable whose bound isn't conformed to.
abstract class ParentDataWidget<T extends RenderObjectWidget> extends ProxyWidget {
                                ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/timetable-0.2.0/lib/src/basic.dart:60:36: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
          style: context.textTheme.bodyText2.copyWith(
                                   ^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)

**Environment:**
- Device:  iPhone 11 Pro Max
- OS:  macOS Catalina
- Package version:  timetable: ^0.2.0

**Comment by JonasWanke** [comment]
It looks like you're running an older version of Flutter. Could you please try upgrading to v1.17.0? There were a few breaking changes in that release affecting this package.

**Comment by JonasWanke** [comment]
Sorry that this happened. I have now specified the minimum supported version in `pubspec.yaml` so Pub warns you about an incompatible Flutter version and will add testing across different Flutter versions to prevent similar issues in the future.
