### ISSUE TITLE
AllDayEvents Bar gets large by 1 row while scrolling through the timetable

### ISSUE THREAD

**Issue by iugabogdan98** [JonasWanke/timetable#70]
**Describe the bug**
Having an All Day Event in the current time range and scrolling to the right/left enough to not see the event, or just pressing a button to animate to today, when going back to the current timeframe the All Day event gets by 1 empty row. Each movemnt after that adds one extra empty row 

**Screenshots**

| Landing page of timetable has All Day Event   | Scroll through the timetable, an extra row appears  | Every movement to right/left/today adds a new empty row  |
| :------------: | :------------: |  :------------: |
| 
![image](https://user-images.githubusercontent.com/32670454/120080707-dbdfd580-c0c2-11eb-9777-c9a74e95e1e5.png)
 | ![image](https://user-images.githubusercontent.com/32670454/120080735-f154ff80-c0c2-11eb-9b1e-cab6497faeb6.png) |
| 
![image](https://user-images.githubusercontent.com/32670454/120080776-18abcc80-c0c3-11eb-8567-67abda865803.png)
|
-->

**Environment:**

- Device:  Pixel 3a
- OS version:  Android 11
- Package version:  0.2.9

**Comment by iugabogdan98** [comment]
On further testing, one possible problem would be: on each movement, the event is re-generated, but the bar doesn't respond accordingly to the event.
The issue also happens when editing/adding an event, that is handled in another screen

**Comment by JonasWanke** [comment]
That's an interesting behavior, but I think I just found its cause and fixed it as part of the refactoring (issue: #17, PR: #69, commit: https://github.com/JonasWanke/timetable/pull/69/commits/14bb4d2cce95f24fc466d5015d9bc178dcf94009). A first version with that fix should be released very soon.

**Comment by iugabogdan98** [comment]
Thank you, I'll keep an eye for the relaase 👍
