### ISSUE TITLE
Days header sometimes disappear 

### ISSUE THREAD

**Issue by TatsuUkraine** [JonasWanke/timetable#73]
I don't know what is a clear way to reproduce it, since it happens time to time on a week view somewhere around Feb 2021.

**Describe the bug**
Days header disappear during the swipe within the Feb 2021

```dart
TimetableConfig<BasicEvent>(
            eventProvider: (interval) {
              return [
                BasicEvent(
                  title: interval.start.toString(),
                  id: interval.start.toString(),
                  start: interval.start.atStartOfDay.add(const Duration(hours: 1)),
                  end: interval.start.atStartOfDay.add(const Duration(hours: 2)),
                  backgroundColor: Colors.red,
                ),
                BasicEvent(
                  title: interval.end.toString(),
                  id: interval.end.toString(),
                  start: interval.end.atStartOfDay.add(const Duration(hours: 1)),
                  end: interval.end.atStartOfDay.add(const Duration(hours: 2)),
                  backgroundColor: Colors.blue,
                ),
              ];
            },
            eventBuilder: (context,  event) => Container(
              color: event.backgroundColor,
            ),
            child: MultiDateTimetable<BasicEvent>(),
          ),
```

**Screenshots**

Don't look at the header) it's actually Feb, not Jun)

![header-issue](https://user-images.githubusercontent.com/621542/121390172-c9cd2500-c955-11eb-9f90-5837fa85a960.gif)

**Environment:**
- Package version:  1.0.0-alpha.0

**Comment by JonasWanke** [comment]
The `DatePageView` that contains the `DateHeader` widgets internally stores the heights of its inner widgets in order to shrink-wrap to their heights. I'd guess that either the widgets temporarily report a height of zero for some reason, or that entries are removed from the internal cache too eagerly. But so far, I have no clue why either of them could occur and have not been able to reproduce this issue myself either.

**Comment by TatsuUkraine** [comment]
Yeah, I don't have a clear reproduction steps either. But it happens on real device in profile mode and on emulator in debug mode. Strange thing also that it happens also on a different weeks. First time I noticed it it was on last week of Feb, after some time it started to appear on one week before etc

**Comment by TatsuUkraine** [comment]
Also in some cases it headers was hiding during the scroll and then appear when scroll ends, and sometimes header was hidden permanently on following 2 weeks etc. So quite strange behavior

**Comment by TatsuUkraine** [comment]
https://user-images.githubusercontent.com/621542/121394965-93de6f80-c95a-11eb-81b8-add35d5d3e16.MP4

**Comment by TatsuUkraine** [comment]
can't reproduce it anymore
