### ISSUE TITLE
Customize time format & Select specific time range

### ISSUE THREAD

**Issue by MasterHiei** [JonasWanke/timetable#74]
@JonasWanke Hi, thank you for your amazing package! I have several questions that I would like to ask you.
1. Can I customize the time format such as 24-hour clock? 
**Update** -> I created a PR(#82) for resolving it
2. Can I select a time range with some gestures(like tap & swipe)?
**Update** -> The `PartDayDraggableEvent` looks good
3. Can I show the start and the end time(00:00 ~ 00:00(24:00), not 1:00 ~ 23:00)?

Many thanks.

**Comment by JonasWanke** [comment]
1. For anyone finding this in the future: By default, the time format including 12- vs. 24-hour format depends on the current locale. Using a new parameter added in #82, one can force the 24-hour format:

    ```dart
    TimetableThemeData(
      context,
      timeIndicatorStyleProvider: (time) =>
          TimeIndicatorStyle(context, time, alwaysUse24HourFormat: true),
    )
    ```

2. The `PartDayDraggableEvent` can be moved by dragging it, but selecting a start and end time just by dragging is not currently supported.
3. Yes, with the new release [v1.0.0-alpha.2](https://pub.dev/packages/timetable/versions/1.0.0-alpha.2/changelog#100-alpha2--2021-07-15):

    ```dart
    MultiDateTimetable<MyEvent>(
      contentLeading: TimeZoom(
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 8),
          child: Builder(
            builder: (context) => TimeIndicators.hours(
              firstHour: 0,
              lastHour: Duration.hoursPerDay,
              alignFirstAndLastLabelsInside: true,
            ),
          ),
        ),
      ),
    )
    ```
