### ISSUE TITLE
Time indicator won't scroll

### ISSUE THREAD

**Issue by paolovalerdi** [JonasWanke/timetable#77]
The time indicator is not properly aligned below the all-day events container and won't' scroll when setting up `maxRange`

![image](https://user-images.githubusercontent.com/9915479/121545516-384ec900-c9d0-11eb-8f7f-d64bfcfb95c8.png)

- Device:  Web, Android
- OS version:  Android 7 - 11, Chrome, Edge
- Package version:  v1.0.0-alpha.1

**Comment by paolovalerdi** [comment]
This is intended

**Comment by JonasWanke** [comment]
With release [v1.0.0-alpha.2](https://pub.dev/packages/timetable/versions/1.0.0-alpha.2/changelog#100-alpha2--2021-07-15), you can now modify the alignment of just the outer labels so they aren't cut off. However, this is not done automatically based on the maximum range, but has to be done separately:

```dart
MultiDateTimetable<MyEvent>(
  contentLeading: TimeZoom(
    child: Padding(
      padding: EdgeInsets.symmetric(horizontal: 8),
      child: TimeIndicators.hours(
        firstHour: 8,
        lastHour: 20,
        alignFirstAndLastLabelsInside: true,
      ),
    ),
  ),
)
```
