### ISSUE TITLE
Vertical scroll does not work inside SliverToBoxAdapter

### ISSUE THREAD

**Issue by mirabu2801** [JonasWanke/timetable#80]
Thank you for this amazing package. 
I faced a problem: vertical scroll does not work inside SliverToBoxAdapter

Example:

    return Scaffold(
      body: CustomScrollView(slivers: [
        SliverToBoxAdapter(
          child: Container(
            height: 500,
            child: TimetableConfig<Event>(
              eventProvider: (_) => [],
              eventBuilder: (_, __) => Container(),
              child: MultiDateTimetable(),
            ),
          ),
        ),
      ]),
    );

**Environment:**

- Device:  Nokia 7.2
- OS version:  Android 10
- Package version:  v1.0.0-alpha.1

**Comment by mirabu2801** [comment]
@JonasWanke ?

**Comment by JonasWanke** [comment]
I can reproduce this problem and have identified the cause: a scroll gesture is accepted with less pointer movement than a pan gesture, and hence the outer scroll view always wins the gesture arena when there's only one pointer on the screen. However, I did not yet have the time to implement a workaround (that would likely consist of copying the `ScaleGestureRecognizer` and changing when it accepts the gesture).

**Comment by JonasWanke** [comment]
This is now fixed as part of [v1.0.0-alpha.3](https://pub.dev/packages/timetable/versions/1.0.0-alpha.3/changelog#100-alpha3--2021-08-02)

**Comment by mirabu2801** [comment]
Great! Thank you
