### ISSUE TITLE
Fast way to reload current range.

### ISSUE THREAD

**Issue by SApolinario** [JonasWanke/timetable#85]
Hi, I love this package.  Thank you!

I'm currently using EventProvider.stream to load my events.  I also provide the user with a way to filter which type of events get displayed.  As the filter get's updated I would like to simply refresh the current view with the appropriate events.  Is there a simple way to refresh the current range of events.  I basically need to clear out the given range and reload from local storage with applied filtering.  Any suggestions would be welcome.

Thanks

Samuel

**Comment by JonasWanke** [comment]
Hi Samuel, great to hear that! Updating the events based on the filter should be possible using a `StreamController` that contains the current filter and updates the events (old events are overridden). Here's an example of how it could work, though I haven't tested it:

```dart
// A stream controller that sends out an event every time the filter is changed.
// Don't forget to dispose it!
final filterStreamController = StreamController<MyFilter>();

// When the user changes the filter, update the stream controller.
void updateFilter(MyFilter filter) => filterStreamController.add(filter);

final eventProvider = EventProvider.stream(
  eventGetter: (range) => filterStreamController.stream
      .map((filter) => getEventsForFilterAndRange(filter, range))),
);
```

**Comment by SApolinario** [comment]
Thanks Jonas!  That did the trick.  It's working as expected.
