### ISSUE TITLE
Issue: Week number

### ISSUE THREAD

**Issue by akabisdev** [JonasWanke/timetable#86]
When we open the timetable widget with week view it show the correct week number,
 * if we swipe to the right, the week number doesn't update.. and if we swipe back to current week, week number decreases by one
 for example : Today is 6 July 2021 : week number 27, week range : 5 July - 11 July
if we swipe right, week number 27, week range: 12 July - 18 July
and now if we swipe back, week number 26, week range: 5 July - 11 July
 
* if we swipe left, week number decrease by 2.
for example : Today is 6 July 2021 : week number 27, week range : 5 July - 11 July
if we swipe left, week number 25, week range: 28 Jun - 4 July
and now if we swipe back, week number 26, week range: 5 July - 11 July

It can be seen in the doc as well.
 
![image](https://user-images.githubusercontent.com/84234310/124553417-57ffd280-de52-11eb-96c9-cbf36198b5df.png)

**Environment:**

- Device:  Asus Max Pro M2
- OS version:  Android 9.0.0
- Package version:  v1.0.0-alpha.1

**Comment by JonasWanke** [comment]
The reported position was something like `18861.9999999851` (instead of `18862`) and hence the week number of the previous week was shown. This is now fixed in release [v1.0.0-alpha.2](https://pub.dev/packages/timetable/versions/1.0.0-alpha.2/changelog#100-alpha2--2021-07-15).
