### ISSUE TITLE
Hide and disable week indicator

### ISSUE THREAD

**Issue by tech-119** [JonasWanke/timetable#97]
How can week indicator be removed/hidden and disabled? 
![image](https://user-images.githubusercontent.com/88559046/129344811-a0cee524-9b6a-4a12-82b1-056c51fde624.png)

There is option to change styling of week indicator, but what about removing it?
```dart
weekIndicatorStyleProvider: (week) => 
    WeekIndicatorStyle(context, week, labels: , textStyle: , tooltip: , padding: , decoration: ),
```

**Comment by JonasWanke** [comment]
In [`MultiDateTimetable`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/MultiDateTimetable-class.html), you can override the [`headerBuilder`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/MultiDateTimetable/headerBuilder.html):

```dart
MultiDateTimetable<E>(
  headerBuilder: (header, leadingWidth) => MultiDateTimetableHeader<E>(
    leading: SizedBox(
      width: leadingWidth,
      child: // In the normal widget, this would be `WeekIndicator.forController(null)`.
      // You can replace it with any widget you want, or just leave it empty.
    ),
  ),
)
```

**Comment by tech-119** [comment]
> In [`MultiDateTimetable`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/MultiDateTimetable-class.html), you can override the [`headerBuilder`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/MultiDateTimetable/headerBuilder.html):
> 
> ```dart
> MultiDateTimetable<E>(
>   headerBuilder: (header, leadingWidth) => MultiDateTimetableHeader<E>(
>     leading: SizedBox(
>       width: leadingWidth,
>       child: // In the normal widget, this would be `WeekIndicator.forController(null)`.
>       // You can replace it with any widget you want, or just leave it empty.
>     ),
>   ),
> )
> ```

Thank you that worked I have set it to null!

And similarly weeks inside `CompactMonthTimetable` be removed as well? I have tried to find something i could possibly use but does not seem there is some method as with  `[MultiDateTimetable](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/MultiDateTimetable-class.html)`
![image](https://user-images.githubusercontent.com/88559046/129365907-b58eb1e4-e6e5-46d6-84c1-110f0c12ee80.png)

**Comment by JonasWanke** [comment]
That should be possible with the following code. It first removes the individual week indicators (replacing them with `SizedBox.shrink()`), and then also removes the outer decoration and padding:

```dart
TimetableConfig<BasicEvent>(
  child: CompactMonthTimetable(
    monthBuilder: (context, month) => MonthWidget(
      month,
      weekBuilder: (context, week) => SizedBox.shrink(),
    ),
  ),
  theme: TimetableThemeData(
    context,
    monthWidgetStyleProvider: (month) => MonthWidgetStyle(
      context,
      month,
      weeksDecoration: BoxDecoration(),
      weeksPadding: EdgeInsets.zero,
    ),
  ),
)
```

**Comment by tech-119** [comment]
@JonasWanke Thank you that is exactly what I needed:
![image](https://user-images.githubusercontent.com/88559046/129369445-cb7ab0f5-47d4-4e91-8486-813e02a3c8ee.png)

As last question, can I also programmatically move between months in [`CompactMonthTimetable`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/CompactMonthTimetable-class.html) widget? For example on 2 buttons, previous/next? Does it expose controller or similar that i could use?

**Comment by JonasWanke** [comment]
The `CompactMonthTimetable` syncs itself to the ambient [`DateController`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/DateController-class.html) it finds via `DefaultDateController.of(context)`, if available. That could come from a [`DefaultDateController`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/DefaultDateController-class.html) widget directly, or from a [`TimetableConfig`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/TimetableConfig-class.html). So, by calling [`dateController.animateTo(date)`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/DateController/animateTo.html), the month is updated as well.

If you don't want to use a  `DateController` for that, `CompactMonthTimetable` is just a `MonthPageView` synced to the ambient date controller displaying `MonthWidget`s. Therefore, you could also build it yourself:

```dart
final monthController = MonthPageController(
  initialMonth: DateTimeTimetable.currentMonth(),
);

MonthPageView(
  monthPageController: monthController ,
  shrinkWrapInCrossAxis: true,
  builder: (context, month) => MonthWidget(context, month),
)
```

**Comment by tech-119** [comment]
@JonasWanke I have tried to create a simple button with `dateController.animateTo(date)` callback and for some reason I get an error saying _"package:timetable/src/utils.dart': Failed assertion: line 140 pos 12: 'isValidTimetableDateTime': is not true"_

Code: ```dart
ElevatedButton(
  onPressed: () => _dateController.animateTo(
    DateTime(2021, 9, 7, 17, 30),
    vsync: this,
  ),
  child: Text("go to SEPTEMBER"),
),
```

Stack trace: ```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:timetable/src/utils.dart': Failed assertion: line 140 pos 12: 'isValidTimetableDateTime': is not true.

When the exception was thrown, this was the stack
#2      DateTimeTimetable.page
package:timetable/src/utils.dart:140
#3      DateController.animateTo
package:timetable/…/date/controller.dart:76
#4      _TimetableExampleState.build.<anonymous closure>
package:odin_mobile/main.dart:164
#5      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:989
#6      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:182
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#41514
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(209.9, 43.4)
    finalLocalPosition: Offset(77.7, 13.4)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

```

**Comment by JonasWanke** [comment]
From the README:

> Timetable doesn't care about any time-zone related stuff. All supplied `DateTime`s must have `isUtc` set to `true`, but the actual time zone is then ignored when displaying events.
>
> Some date/time-related parameters also have special suffixes:
>
> * `date`: A `DateTime` with a time of zero.
> […]

The `DateTime` you passed is neither in UTC nor has it a time of zero. You could either use `DateTime.utc(2021, 9, 7)` or Timetable's [`DateTimeTimetable.date(2021, 9, 7)`](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/DateTimeTimetable/date.html).

**Comment by tech-119** [comment]
@JonasWanke I read and forgot about readme, using utc worked thank you once again everything is resolved. 

Closing issue
