### ISSUE TITLE
Implement CompactMonthTimetable in showDialog

### ISSUE THREAD

**Issue by tech-119** [JonasWanke/timetable#98]
I'm trying to implement [CompactMonthTimetable](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/CompactMonthTimetable-class.html) inside flutter's [showGeneralDialog](https://api.flutter.dev/flutter/widgets/showGeneralDialog.html) function, but error i'm receiving is pointing at the line **346** saying **_Null check operator used on a null value_**
`346| callbacks: DefaultTimetableCallbacks.of(dialogContext)!.copyWith(`:

![image](https://user-images.githubusercontent.com/88559046/129540017-c33ad832-cf75-4542-9d17-7f2bea53afb3.png)

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building Builder(dirty):
Null check operator used on a null value

The relevant error-causing widget was
Builder
package:app_mobile/main.dart:344
When the exception was thrown, this was the stack
#0      _TimetableExampleState._buildAppBar.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:app_mobile/main.dart:346
#1      Builder.build
package:flutter/…/widgets/basic.dart:7798
#2      StatelessElement.build
package:flutter/…/widgets/framework.dart:4648
#3      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4574
#4      Element.rebuild
package:flutter/…/widgets/framework.dart:4267
...
```
**Code with showGeneralDialog (error appears)**
```dart
154|  @override
155|  Widget build(BuildContext context) {
156|    return TimetableConfig<BasicEvent>(
157|      // Required:
158|      dateController: _dateController,
159|      timeController: _timeController,
160|      eventBuilder: (context, event) => _buildPartDayEvent(event),
161|      child: Column(children: [
162|        _buildAppBar(context), // here is the error
163|        Expanded(
164|            child: MultiDateTimetable<BasicEvent>(
165|          headerBuilder: (header, leadingWidth) => SizedBox.shrink(),
166|        )
167|   // .....


333| Widget _buildAppBar(BuildContext context) {
334|  child = InkWell(
335|    onTap: () => showGeneralDialog(
336|      context: context,
337|      pageBuilder: (
338|        BuildContext dialogContext,
339|        Animation<double> animation,
340|        Animation<double> secondaryAnimation,
341|      ) =>
342|          Padding(
343|        padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
344|        child: Builder(builder: (builderContext) {
345|          return DefaultTimetableCallbacks(
346|            callbacks: DefaultTimetableCallbacks.of(dialogContext)!.copyWith(
347|              onDateTap: (date) {
348|                _updateVisibleDateRange(PredefinedVisibleDateRange.day);
349|                _dateController.animateTo(date, vsync: this);
350|              },
351|            ),
352|            child: CompactMonthTimetable(
353|              monthBuilder: (monthContext, month) => MonthWidget(
354|                month,
355|                weekBuilder: (weekContext, week) => SizedBox.shrink(),
356|              ),
357|            ),
358|          );
359|        }),
360|      ),
361|      /* CompactMonthTimetableDialog(
362|                timetableContext: context,
363|                dateController: _dateController,
364|                updateVisibleDateRange: _updateVisibleDateRange,
365|              ), */
366|    ),
367|    child: MonthIndicator.forController(_dateController),
368|  );
367| }
```

Now when I use it normally without `showGeneralDialog` it displays well, so I want to encapsulate this child from `_buildAppBar` widget so that it's inside `showGeneralDialog` which I would then show on user action (on press)

**Code without showGeneralDialog (displayed well)**

```dart
@override
Widget build(BuildContext context) {
  return TimetableConfig<BasicEvent>(
    // Required:
    dateController: _dateController,
    timeController: _timeController,
    eventBuilder: (context, event) => _buildPartDayEvent(event),
    child: Column(children: [
      _buildAppBar(context),
      Expanded(
          child: MultiDateTimetable<BasicEvent>(
        headerBuilder: (header, leadingWidth) => SizedBox.shrink(),
      )

Widget _buildAppBar(BuildContext context) {
  child = Padding(
    padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
    child: Builder(builder: (context) {
      return DefaultTimetableCallbacks(
        callbacks: DefaultTimetableCallbacks.of(context)!.copyWith(
          onDateTap: (date) {
            _updateVisibleDateRange(PredefinedVisibleDateRange.day);
            _dateController.animateTo(date, vsync: this);
          },
        ),
        child: CompactMonthTimetable(
          monthBuilder: (context, month) => MonthWidget(
            month,
            weekBuilder: (context, week) => SizedBox.shrink(),
          ),
        ),
      );
    }),
  );

  return child;
}
      ```

**Comment by JonasWanke** [comment]
Widgets inside `showGeneralDialog` don't have access to the outside context. From the documentation: "The widget returned by the pageBuilder does not share a context with the location that showGeneralDialog is originally called from." Therefore, DefaultTimetableCallbacks can't find the outer inherited widget bis `.of(context)`. Instead, you can pass the default callbacks manually into `_buildAppBar` or call `.of(context)` outside the dialog

**Comment by tech-119** [comment]
> Widgets inside `showGeneralDialog` don't have access to the outside context. From the documentation: "The widget returned by the pageBuilder does not share a context with the location that showGeneralDialog is originally called from." Therefore, DefaultTimetableCallbacks can't find the outer inherited widget bis `.of(context)`. Instead, you can pass the default callbacks manually into `_buildAppBar` or call `.of(context)` outside the dialog

Thank you for answer, I have managed to display it inside `showGeneralDialog` although with size issues and some issues so i decided to use it directly instead and show/hide it on state change.

One thing about styling I couldn't figure out is can we modify splash radius of date numbers in [CompactMonthTimetable](https://pub.dev/documentation/timetable/1.0.0-alpha.5/timetable/CompactMonthTimetable-class.html) widget?

**Comment by tech-119** [comment]
> You could supply the `dateBuilder` parameter of `MonthWidget`and build the inner widget yourself, e.g., by wrapping a `DateIndicator` without a callback in a customized `InkResponse`

Thank you that did what I desired!
